### ISSUE TITLE
Error when attempting to create new project

### ISSUE THREAD

**Issue by waymobetta** [Arch-Network/arch-cli#22]
I receive the following when trying to create a new project. Also curious what the difference is between `init` subcommand and `project create` and when I would use one over the other.

Looks like the project dir [should be created if it doesn't already exist](https://github.com/Arch-Network/arch-cli/blob/main/src/lib.rs#L530), but I wasn't prompted for a directory even when running without the `--name` flag.

```
jr@waymobetta arch-cli % arch-cli project create -n my_app
Welcome to the Arch Network CLI
  → Loading configuration from /Users/jr/Library/Application Support/arch-cli/config.toml
Creating a new project...
Error: Failed to get project directory from config
```

**Comment by hoffmabc** [comment]
Init sets up the configuration directory, creates the project directory if it doesn't exist and then copies in the demo application into that project directory.

`project create` should just create another application folder in the application directory wherever the user has created it.

**Comment by waymobetta** [comment]
When you clone the repo the `/app` directory and demo app logic content already exist under `/src` which is why I was confused. I would understand if this didn't exist originally and then `init` would make use of the templates and copy in the demo app but then why does it already exist at clone?
